# https://github.com/golangci/golangci-lint
name: Lint & Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint

    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x,]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch version.
          # https://github.com/golangci/golangci-lint/releases
          version: v1.39
  
  test:
    name: Unit Tests

    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x,]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    needs:
      - lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - run: go test ./...